Assignments/boolean birds
bhs-intro-to-programming/MaxZoidis pull request #1
Opened 2022-09-09 21:40 UTC by MaxZoidis

2022-09-10 02:23 UTC, gigamonkey requested changes
Please make the changes I suggested in the comment and I'll re-review this.

2022-09-10 02:23 UTC, gigamonkey commented on assignments/boolean-birds/code.js
> +function isRed (s1){
Why did you suddenly switch to this syntax here. Please rewrite these functions to use the same syntax as you used for early functions. You should also right click somewhere in the editor to get the context menu and select 'Format document' to fix up a bunch of small formatting issues. It's good to get used to seeing well formatted code because then it gets easier to see problems in code (especially when the auto formatter formats weirdly because you missed a brace or something.)

2022-09-14 00:14 UTC, gigamonkey commented on assignments/boolean-birds/code.js
> +function isRed (s1){
You should still run the auto formatter is the editor—some of this indentation is still pretty wonky. Ask me for help if you missed the explanation yesterday about how to do that.

2022-09-19 21:54 UTC, merged

2022-09-20 21:50 UTC, MaxZoidis commented on assignments/boolean-birds/code.js
> +function isRed (s1){
This is because Ion was helping me with this problem and so this is how he did his.